apiVersion: v1
kind: Service
metadata:
  name: client-portal
  labels:
    app: client-portal
spec:
  type: ClusterIP
  selector:
    app: client-portal
  ports:
    - name: http
      port: 80
      targetPort: 80
