global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'workers'
    static_configs:
      - targets: ['workers:9090']  # replace with actual exporter endpoints
