apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ${REGISTRY}/sam-backend:${TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            [
              {
                "name": "DATABASE_URL",
                "value": "$(DATABASE_URL)"
              },
              {
                "name": "REDIS_URL",
                "value": "$(REDIS_URL)"
              }
            ]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
