services:
  backend:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    image: ${REGISTRY:-local}/sam-backend:${TAG:-dev}
    env_file:
      - ./common.env
    environment:
      - UVICORN_WORKERS=2
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sam
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sam}
      - POSTGRES_USER=${POSTGRES_USER:-sam}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sam}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sam} -d ${POSTGRES_DB:-sam}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    networks:
      - sam
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
# Keycloak removed - using simple JWT authentication instead
# Uncomment the following section if you want to use Keycloak:
#   keycloak:
#     image: quay.io/keycloak/keycloak:22.0.1
#     container_name: keycloak
#     command: start-dev
#     environment:
#       - KEYCLOAK_ADMIN=admin
#       - KEYCLOAK_ADMIN_PASSWORD=admin
#       - KC_HOSTNAME=localhost
#       - KC_HEALTH_ENABLED=true
#       - KC_METRICS_ENABLED=true
#     ports:
#       - "8081:8080"
#     networks:
#       - sam
#     volumes:
#       - ./towerco-realm.json:/opt/keycloak/data/import/realm.json

networks:
  sam:

volumes:
  pgdata: