services:
  frontend:
    build:
      context: ../..
      dockerfile: frontend/Dockerfile
    image: ${REGISTRY:-local}/sam-frontend:${TAG:-dev}
    ports:
      - "8090:8000"
    networks:
      - sam
networks:
  sam:
