services:
  backend:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    image: ${REGISTRY:-local}/sam-backend:${TAG:-dev}
    env_file:
      - ./common.env
    environment:
      - UVICORN_WORKERS=2
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    networks:
      - sam
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sam}
      - POSTGRES_USER=${POSTGRES_USER:-sam}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sam}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sam} -d ${POSTGRES_DB:-sam}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    networks:
      - sam
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=h2
      - KC_DB_URL=jdbc:h2:mem:keycloak
    ports:
      - "8081:8080"
    networks:
      - sam
    volumes:
      - ./towerco-realm.json:/opt/keycloak/data/import/realm.json
    # Keycloak utilise H2 en mémoire, pas besoin de PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  sam:

volumes:
  pgdata: