services:
  backend:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    image: ${REGISTRY:-local}/sam-backend:${TAG:-dev}
    env_file:
      - ./common.env
    environment:
      - UVICORN_WORKERS=2
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      keycloak:
        condition: service_healthy
    networks:
      - sam
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sam}
      - POSTGRES_USER=${POSTGRES_USER:-sam}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sam}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sam} -d ${POSTGRES_DB:-sam}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    networks:
      - sam
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    ports:
      - "8081:8080"
    networks:
      - sam
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8080 && printf \"GET /health/ready HTTP/1.0\\r\\n\\r\\n\" >&3 && head -n1 <&3 | grep -q \"200\"'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 45s

networks:
  sam:

volumes:
  pgdata: