services:
  backend:
    build:
      context: ../..
      dockerfile: backend/Dockerfile
    image: ${REGISTRY:-local}/sam-backend:${TAG:-dev}
    env_file:
      - ./common.env
    environment:
      - UVICORN_WORKERS=2
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - sam
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-sam}
      - POSTGRES_USER=${POSTGRES_USER:-sam}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-sam}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-sam} -d ${POSTGRES_DB:-sam}"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    networks:
      - sam
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      #- KEYCLOAK_ADMIN=admin
      #- KEYCLOAK_ADMIN_PASSWORD=admin
      #- KC_HOSTNAME=${KEYCLOAK_HOSTNAME:-37.60.242.104:8081}
      #- KC_HEALTH_ENABLED=true
      #- KC_METRICS_ENABLED=true
      #- KC_HOSTNAME_STRICT=false
      #- KC_HOSTNAME_STRICT_HTTPS=false
      #- KC_HTTP_ENABLED=true
      #- KC_PROXY=edge
      #- KC_LOG_LEVEL=WARN
      #- KC_IMPORT_REALM=true
      #- KC_SPI_LOGIN_PROTOCOL_OPENID_CONNECT_SUPPRESS_LOGOUT_CONFIRMATION_SCREEN=true
      #- KC_FEATURES=token-exchange,admin-fine-grained-authz
      #- KC_CACHE=local
      #- KC_FEATURES_DISABLED=step-up-authentication
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      
      # External access configuration (from common.env)
      - KC_HOSTNAME=${KEYCLOAK_EXTERNAL_HOST}
      - KC_HOSTNAME_ADMIN=${KEYCLOAK_EXTERNAL_HOST}
      - KC_FRONTEND_URL=${KEYCLOAK_EXTERNAL_PROTOCOL}://${KEYCLOAK_EXTERNAL_HOST}:${KEYCLOAK_EXTERNAL_PORT}
      
      # Protocol configuration
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_ADMIN_STRICT=false
      - KC_HOSTNAME_ADMIN_STRICT_HTTPS=false
      
      # Features and performance
      - KC_FEATURES=hostname:v2,token-exchange,admin-fine-grained-authz
      - KC_FEATURES_DISABLED=step-up-authentication
      - KC_CACHE=local
      
      # Observability
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_LOG_LEVEL=WARN
      
      # Debug (optional)
      - KC_HOSTNAME_DEBUG=true


    ports:
      - "8081:8080"
    networks:
      - sam
    volumes:
      - ./towerco-realm.json:/opt/keycloak/data/import/realm.json
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 120s

networks:
  sam:

volumes:
  pgdata: