apiVersion: v1
kind: Service
metadata:
  name: workers
  labels:
    app: workers
spec:
  type: ClusterIP
  selector:
    app: workers
  ports:
    - name: http
      port: 8000
      targetPort: 8000
